'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Box,RotateCcw,Move3D,Link2,Unlink,ScanLine,Layers,BookOpen,Compass,ArrowRight,Minus,Plus,Info,X,Check,ChevronLeft,ChevronRight} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import LatticeView,{type Camera,type ViewOptions} from './lattice-view';
import {basis,defaultCell,presets,transform,norm,dot,unit,type Cell,type Vec} from '@/lib/lattice';
const defaultCamera:Camera={yaw:-1.05,el:.48,zoom:1};
const lessons=[
 {title:'Stretch the crystal',subtitle:'Bigger here. Smaller there.',steps:[{title:'Start with a 4 Å cubic cell',text:'The (100) planes are 4 Å apart. Their reciprocal point sits 0.250 Å⁻¹ from the origin. Notice the scale bars in each view.',h:[1,0,0],cell:defaultCell},{title:'Double only a',text:'a is now 8 Å. The (100) plane spacing doubles, while the reciprocal point moves halfway toward the origin. b and c stay unchanged.',h:[1,0,0],cell:{...defaultCell,a:8}},{title:'Try it yourself',text:'Move the a slider. Watch d₁₀₀ and |g₁₀₀| change together: their product stays 1. The view does not automatically rescale.',h:[1,0,0],cell:{...defaultCell,a:6}}]},
 {title:'100 → 200',subtitle:'Same direction. Twice the frequency.',steps:[{title:'One repeat per unit-cell length',text:'For this cubic cell, (100) gives d = 4 Å. The reciprocal vector follows a*.',h:[1,0,0],cell:defaultCell},{title:'Two repeats per unit-cell length',text:'For (200), d = 2 Å and |g| = 0.500 Å⁻¹. The vector doubles in length without changing direction. Intermediate planes need not contain lattice points.',h:[2,0,0],cell:defaultCell},{title:'Reverse the sign',text:'The point (−200) lies in the opposite direction. The unoriented set of parallel planes and its spacing are unchanged.',h:[-2,0,0],cell:defaultCell}]},
 {title:'Turn the planes',subtitle:'Read orientation from a point.',steps:[{title:'A face-parallel set: (100)',text:'The plane normal lies along a*. Choose “Edge-on planes” to make the spacing especially clear.',h:[1,0,0],cell:defaultCell},{title:'A diagonal set: (110)',text:'Adding b* turns the normal. For a cubic cell, d₁₁₀ = a/√2. The point is farther from O, and the planes are closer together.',h:[1,1,0],cell:defaultCell},{title:'A body-diagonal normal: (111)',text:'Now g = a* + b* + c*. For this cubic cell, d₁₁₁ = a/√3 = 2.309 Å. Rotate either view to compare the orientation.',h:[1,1,1],cell:defaultCell}]},
 {title:'Skew the cell',subtitle:'Reciprocal axes are a dual basis.',steps:[{title:'Begin with perpendicular axes',text:'In an orthogonal cell, a* is parallel to a. That shortcut does not hold for every crystal system.',h:[1,0,0],cell:defaultCell},{title:'Tilt b toward a',text:'With γ = 65°, a* stays perpendicular to b and c, so it tilts away from a. Its magnitude is 1/(a sin γ) in this example.',h:[1,0,0],cell:{...defaultCell,gamma:65}},{title:'Explore a triclinic cell',text:'All three reciprocal axes are calculated from the real basis. a* is normal to the b–c plane, b* to c–a, and c* to a–b.',h:[1,1,1],cell:presets.Triclinic}]},
 {title:'Direction ≠ normal',subtitle:'[hkl] and (hkl) use different bases.',steps:[{title:'They align in a cubic cell',text:'The purple [110] direction and gold plane normal overlap here. Cubic geometry makes their directions coincide.',h:[1,1,0],cell:defaultCell},{title:'Stretch one axis',text:'In this orthorhombic cell, [110] = a + b tilts toward the longer b axis. The plane normal a* + b* tilts toward a*. They separate.',h:[1,1,0],cell:{...defaultCell,b:7}},{title:'Inspect the angle',text:'The live angle below compares the two vectors. The gold normal always stays perpendicular to the planes; the purple direction generally does not.',h:[1,1,0],cell:{...defaultCell,b:7}}]}
];
function Range({label,value,min,max,step=1,onChange,unitText='',disabled=false}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;unitText?:string;disabled?:boolean}){
 return <div className={'range-row'+(disabled?' disabled':'')}><label>{label}</label><Slider aria-label={label} disabled={disabled} min={min} max={max} step={step} value={[value]} onValueChange={v=>onChange(v[0])}/><div className="number-wrap"><input aria-label={`${label} value`} type="number" disabled={disabled} value={value} min={min} max={max} step={step} onChange={e=>{if(e.target.value==='')return;const x=Number(e.target.value);if(Number.isFinite(x)&&x>=min&&x<=max)onChange(Number((Math.round(x/step)*step).toFixed(6)));}}/><span>{unitText}</span></div></div>
}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="toggle-row"><span>{label}</span><Switch aria-label={label} checked={checked} onCheckedChange={onChange}/></label>}
export default function ReciprocalLab(){
 const [cell,setCell]=useState<Cell>({...defaultCell});const [system,setSystem]=useState('Cubic');const [h,setH]=useState<Vec>([1,1,0]);const [factor,setFactor]=useState(1);const [camera,setCamera]=useState<Camera>({...defaultCamera});const [otherCamera,setOtherCamera]=useState<Camera>({...defaultCamera});const [linked,setLinked]=useState(true);
 const [options,setOptions]=useState<ViewOptions>({planes:true,points:true,labels:true,direction:false,slice:false,opacity:.24});const [mode,setMode]=useState('explore');const [lesson,setLesson]=useState(0);const [step,setStep]=useState(0);const [error,setError]=useState('');
 const geometry=useMemo(()=>basis(cell),[cell]);const g=transform(geometry.reciprocal,h),length=norm(g),d=length>1e-10?1/length:null;const angle=d?Math.acos(Math.max(-1,Math.min(1,dot(unit(g),unit(transform(geometry.direct,h))))))*180/Math.PI:0;
 const symbol=factor===1?'g':'G';const hText=h.join(' ');const val=(v:number,n=3)=>v.toFixed(n);const setOption=(key:keyof ViewOptions,value:boolean|number)=>setOptions(o=>({...o,[key]:value}));
 function changeCell(key:keyof Cell,value:number){let next={...cell,[key]:value};if(system==='Cubic'&&['a','b','c'].includes(key))next={...next,a:value,b:value,c:value};if(['Tetragonal','Hexagonal'].includes(system)&&(key==='a'||key==='b'))next={...next,a:value,b:value};try{basis(next);setCell(next);setError('');}catch(e){setError((e as Error).message);}}
 function reset(){setCell({...defaultCell});setSystem('Cubic');setH([1,1,0]);setCamera({...defaultCamera});setOtherCamera({...defaultCamera});setOptions({planes:true,points:true,labels:true,direction:false,slice:false,opacity:.24});setFactor(1);setLinked(true);setMode('explore');setError('');}
 function startLesson(i:number,s=0){const l=lessons[i].steps[s];setLesson(i);setStep(s);setMode('learn');setCell({...l.cell});setSystem('Custom');setH(l.h as Vec);setFactor(1);setOptions(o=>({...o,planes:true,points:true,direction:i===4,slice:false}));setCamera({...defaultCamera});setOtherCamera({...defaultCamera});setLinked(true);setError('');}
 function align(edge=false){if(!d)return;const n=unit(g);let yaw=Math.atan2(n[1],n[0]),el=Math.asin(n[2]);if(edge){yaw+=Math.PI/2;el=0;}setCamera({...camera,yaw,el});if(linked)setOtherCamera({...camera,yaw,el});setOption('slice',false);}
 const stateRef=useRef({cell,h,factor});stateRef.current={cell,h,factor};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o?:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
 const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'inspect_lattice',description:'Read the displayed cell, selected indices, reciprocal vector and spacing.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const s=stateRef.current,b=basis(s.cell),v=transform(b.reciprocal,s.h),n=norm(v);return {...s,reciprocalVector:v.map(x=>x*s.factor),spacing:n?1/n:null};}});
 register({name:'select_lattice_planes',description:'Select integer Miller indices in both visible lattice views.',inputSchema:{type:'object',properties:{h:{type:'integer',minimum:-4,maximum:4},k:{type:'integer',minimum:-4,maximum:4},l:{type:'integer',minimum:-4,maximum:4}},required:['h','k','l'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{h:number;k:number;l:number})=>{const v=[input.h,input.k,input.l];if(v.some(x=>!Number.isInteger(x)||x< -4||x>4))throw new Error('Indices must be integers from −4 to 4.');setH(v as Vec);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {selected:v};}});
 return()=>lifecycle.abort();},[]);
 return <main className="app-shell">
  <header className="topbar"><a className="brand" href="./" aria-label="Reciprocal Lab home"><span className="brand-icon"><Box size={23}/></span><span>Reciprocal<span className="brand-light"> Lab</span></span></a><div className="course-tag">CRYSTALLOGRAPHY <span>/</span> INTERACTIVE ATLAS</div><Dialog><DialogTrigger className="text-button"><Info size={17}/> The geometry</DialogTrigger><DialogContent className="geometry-dialog"><DialogTitle>One crystal. Two descriptions.</DialogTitle><DialogDescription>Real space describes translations. Reciprocal space describes spatial periodicity.</DialogDescription><div className="geometry-copy"><p><b>Build the dual basis</b><br/>a* = (b × c) / V, with V = a · (b × c). Obtain b* and c* by cycling the letters. Thus a* · a = 1 and a* · b = a* · c = 0.</p><p><b>Read a reciprocal point</b><br/>g = ha* + kb* + lc*. The planes satisfy g · r = m for integer m. Their normal follows g; successive planes are separated by d = 1/|g|.</p><p><b>Two conventions</b><br/>Crystallography uses g and 1/d. Physics often uses G = 2πg and 2π/d. Switching conventions rescales reciprocal coordinates and the ruler, preserving the geometry.</p><p><b>Lattice points are not necessarily atoms</b><br/>The views show a primitive translation lattice. A crystal can attach a multi-atom basis to every lattice point. Intensities and extinction rules require that additional structure information.</p><p><b>Higher-order planes</b><br/>(200) is retained as a distinct reciprocal point. Its intermediate planes need not contain lattice points. Reducing 200 to 100 would lose the spatial-frequency information.</p><p><b>View conventions</b><br/>Real space shows a crop of eight unit cells. Reciprocal space shows indices −2 to 2, plus your selected point. The normal arrow in real space indicates direction only. The reciprocal vector has its actual plotted magnitude. α is between b and c; β between a and c; γ between a and b.</p><a href="https://www.iucr.org/what-we-do/education/pamphlets/reciprocal-lattice" target="_blank" rel="noreferrer">Read the IUCr introduction ↗</a></div></DialogContent></Dialog></header>
  <section className="intro"><div><div className="eyebrow">REAL SPACE ↔ RECIPROCAL SPACE</div><h1>A crystal, two perspectives.</h1><p>Move a plane. Follow its normal. See the inverse relationship.</p></div><div className="intro-actions"><Tabs value={mode} onValueChange={v=>{if(v==='learn')startLesson(lesson);else setMode(v);}}><TabsList><TabsTrigger value="explore"><Compass size={16}/> Explore</TabsTrigger><TabsTrigger value="learn"><BookOpen size={16}/> Guided lab</TabsTrigger></TabsList></Tabs><button className="icon-button" onClick={reset} aria-label="Reset all settings" title="Reset all settings"><RotateCcw size={17}/></button></div></section>
  <div className="workspace"><section className="visual-workspace">
   <div className="view-toolbar"><div className="selection-tag"><span className="gold-dot"/> Selected <b>({hText})</b></div><div className="camera-controls"><button className={linked?'mini active':'mini'} onClick={()=>{if(!linked)setOtherCamera(camera);setLinked(!linked);}}>{linked?<Link2 size={14}/>:<Unlink size={14}/>}<span>{linked?'Views linked':'Views independent'}</span></button><button className="mini" onClick={()=>{setCamera({...defaultCamera});setOtherCamera({...defaultCamera});setOption('slice',false);}}><RotateCcw size={14}/><span>Reset view</span></button></div></div>
   <div className="views"><article className="view-card"><div className="view-heading"><div><span className="panel-number">01</span><h2>Real space</h2></div><span className="unit-badge">Å</span></div><div className="view-description">Parallel planes & their spacing</div><LatticeView kind="real" direct={geometry.direct} reciprocal={geometry.reciprocal} h={h} camera={camera} setCamera={v=>{setCamera(v);if(linked)setOtherCamera(v);}} onSelect={setH} options={options} factor={factor}/><div className="view-bottom"><span><i className="swatch plane"/> ({hText}) planes</span><span><i className="swatch normal"/> Unit normal</span></div></article>
   <article className="view-card reciprocal-card"><div className="view-heading"><div><span className="panel-number">02</span><h2>Reciprocal space</h2></div><span className="unit-badge">Å⁻¹</span></div><div className="view-description">Click a point to reveal its planes</div><LatticeView kind="reciprocal" direct={geometry.direct} reciprocal={geometry.reciprocal} h={h} camera={linked?camera:otherCamera} setCamera={v=>{setOtherCamera(v);if(linked)setCamera(v);}} onSelect={setH} options={options} factor={factor}/><div className="view-bottom"><span><i className="swatch point"/> Reciprocal points</span><span><i className="swatch normal"/> {symbol}<sub>hkl</sub></span></div></article></div>
   <div className="under-view"><span><Move3D size={14}/> Drag to orbit · Scroll to zoom</span><div><button className="mini" disabled={!d} onClick={()=>align(false)}>Look along normal</button><button className="mini" disabled={!d} onClick={()=>align(true)}>Edge-on planes</button><button className="icon-button small" aria-label="Zoom out" onClick={()=>{setCamera(c=>({...c,zoom:Math.max(.35,c.zoom/1.15)}));setOtherCamera(c=>({...c,zoom:Math.max(.35,c.zoom/1.15)}));}}><Minus size={14}/></button><button className="icon-button small" aria-label="Zoom in" onClick={()=>{setCamera(c=>({...c,zoom:Math.min(2.5,c.zoom*1.15)}));setOtherCamera(c=>({...c,zoom:Math.min(2.5,c.zoom*1.15)}));}}><Plus size={14}/></button></div></div>
   <section className="readouts" aria-label="Live lattice measurements"><div><span>PLANE SPACING</span><strong>{d?val(d):'—'} <small>Å</small></strong><p>d<sub>hkl</sub></p></div><div><span>RECIPROCAL LENGTH</span><strong>{val(length*factor)} <small>Å⁻¹</small></strong><p>|{symbol}<sub>hkl</sub>|</p></div><div className="identity"><span>THE CONNECTION</span><strong>d × |{symbol}| = {d?(factor===1?'1':'2π'):'—'}</strong><p>{d?'Closer planes ↔ farther points':'000 is the origin; no plane normal'}</p></div></section>
   <section className="insight"><span className="insight-icon"><Layers size={19}/></span><div><b>{d?'A point encodes a whole set of planes.':'You selected the reciprocal origin.'}</b><p>{d?<>The gold vector is perpendicular to the ({hText}) planes. Its length is {factor===1?'1/d':'2π/d'}, so a larger reciprocal distance means a smaller real-space spacing.</>:<>The 000 point has a zero vector. Choose any nonzero index to define a plane orientation and spacing.</>}</p>{options.direction&&d&&<p className="purple-text">Angle between [hkl] and the plane normal: <b>{val(angle,1)}°</b>. Purple uses the real basis; gold uses the reciprocal basis.</p>}{options.slice&&<p>The section shows real-space intersections with z = 0 and reciprocal points with l = 0. Your selected vector may leave this section.</p>}</div></section>
   {mode==='learn'?<section className="lesson-panel"><div className="section-top"><div><span className="eyebrow">GUIDED EXPERIMENT {String(lesson+1).padStart(2,'0')}</span><h2>{lessons[lesson].title}</h2></div><button className="text-button" onClick={()=>setMode('explore')}><X size={16}/> Exit lesson</button></div><div className="lesson-progress">{lessons[lesson].steps.map((_,i)=><button key={i} className={i===step?'current':i<step?'done':''} onClick={()=>startLesson(lesson,i)} aria-label={`Lesson step ${i+1}`}>{i<step?<Check size={14}/>:i+1}</button>)}</div><h3>{lessons[lesson].steps[step].title}</h3><p>{lessons[lesson].steps[step].text}</p><div className="lesson-nav"><button className="text-button" disabled={step===0} onClick={()=>startLesson(lesson,step-1)}><ChevronLeft size={16}/> Back</button><span>Step {step+1} of 3</span><button className="primary-button" onClick={()=>step<2?startLesson(lesson,step+1):startLesson((lesson+1)%lessons.length,0)}>{step<2?'Next step':'Next experiment'}<ChevronRight size={16}/></button></div></section>:null}
   <section className="experiments"><div className="section-top"><h2>Learn by changing one thing.</h2><span>5 guided experiments</span></div><div className="experiment-grid">{lessons.map((l,i)=><button key={l.title} className={mode==='learn'&&lesson===i?'experiment active':'experiment'} onClick={()=>startLesson(i)}><span className="experiment-number">0{i+1}</span><b>{l.title}</b><p>{l.subtitle}</p><ArrowRight size={16}/></button>)}</div></section>
  </section>
  <aside className="controls"><div className="control-heading"><h2>Crystal controls</h2><span className="live-tag">LIVE</span></div><section className="control-section"><div className="control-label">MILLER INDICES <span>(h k l)</span></div>{h.map((v,i)=><Range key={i} label={['h','k','l'][i]} value={v} min={-4} max={4} onChange={n=>setH(h.map((a,j)=>i===j?n:a) as Vec)}/>)}<div className="quick-indices">{[[1,0,0],[1,1,0],[1,1,1],[2,0,0]].map(v=><button key={v.join('')} className={h.join('')===v.join('')?'selected':''} onClick={()=>setH(v as Vec)}>({v.join('')})</button>)}</div></section>
   <section className="control-section"><div className="control-label">UNIT CELL <span>Primitive lattice</span></div><Select value={system} onValueChange={v=>{setSystem(v);if(presets[v])setCell({...presets[v]});setError('');}}><SelectTrigger aria-label="Crystal system" className="system-select"><SelectValue/></SelectTrigger><SelectContent>{[...Object.keys(presets),'Custom'].map(s=><SelectItem key={s} value={s}>{s==='Custom'?'Custom · independent parameters':s}</SelectItem>)}</SelectContent></Select><div className="lengths">{(['a','b','c'] as const).map(k=><Range key={k} label={k} value={cell[k]} min={2} max={8} step={.1} unitText="Å" disabled={system==='Cubic'&&k!=='a'||['Tetragonal','Hexagonal'].includes(system)&&k==='b'} onChange={v=>changeCell(k,v)}/>)}</div><div className="angles">{(['alpha','beta','gamma'] as const).map((k,i)=><Range key={k} label={['α','β','γ'][i]} value={cell[k]} min={50} max={130} step={1} unitText="°" disabled={!(system==='Custom'||system==='Triclinic'||system==='Monoclinic'&&k==='beta')} onChange={v=>changeCell(k,v)}/>)}</div><p className="control-help">{system==='Cubic'?'Cubic symmetry keeps a = b = c and all angles at 90°.':system==='Custom'?'Each parameter is independent. Invalid angle combinations are rejected.':'Symmetry-linked parameters stay fixed or change together.'}</p>{error&&<p role="alert" className="error">{error}</p>}</section>
   <section className="control-section"><div className="control-label">DISPLAY</div><Toggle label="Plane family" checked={options.planes} onChange={v=>setOption('planes',v)}/><Toggle label="Real lattice points" checked={options.points} onChange={v=>setOption('points',v)}/><Toggle label="Axis & vector labels" checked={options.labels} onChange={v=>setOption('labels',v)}/><Toggle label="Compare [hkl] direction" checked={options.direction} onChange={v=>setOption('direction',v)}/><Toggle label="2D section (z = 0)" checked={options.slice} onChange={v=>setOption('slice',v)}/><div className="opacity-control"><span>Plane opacity</span><Slider aria-label="Plane opacity" min={.08} max={.6} step={.02} value={[options.opacity]} onValueChange={v=>setOption('opacity',v[0])}/></div></section>
   <section className="control-section convention"><div className="control-label">RECIPROCAL CONVENTION</div><Select value={String(factor)} onValueChange={v=>setFactor(Number(v))}><SelectTrigger aria-label="Reciprocal convention" className="system-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1">Crystallography · 1/d</SelectItem><SelectItem value={String(2*Math.PI)}>Physics · 2π/d</SelectItem></SelectContent></Select><p className="control-help">{symbol} = {factor===1?'':'2π('}ha* + kb* + lc*{factor===1?'':')'}<br/>a*, b*, c* here use the crystallographic basis.</p></section>
  </aside></div>
  <footer><span><Box size={14}/> Reciprocal Lab <span className="footer-sep">/</span> Built for understanding.</span><span>Ideal primitive lattices · Geometric model, not diffraction intensity</span></footer>
 </main>
}
